### ISSUE TITLE
Error: No callback provided to pbkdf2

### ISSUE THREAD

**Issue by coolaj86** [OAuth3/oauth3-cli#8]
```
Create a Passphrase (↓ to hide): [oauth3-cli] Error createCredential
Error: No callback provided to pbkdf2
    at Object.exports.pbkdf2 (crypto.js:585:11)
    at /usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/pbkdf2-utils.js:33:12
    at Promise._execute (/usr/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/usr/lib/node_modules/daplie-tools/node_modules/bluebird/js/release/promise.js:77:14)
    at getProofOfSecret (/usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/pbkdf2-utils.js:32:10)
    at Object.A3.createCredential (/usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/utils.js:302:10)
    at Object.CLI.createCredential (/usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:1312:6)
    at loginHelper (/usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:2175:11)
    at loopit (/usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:2142:5)
    at /usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:966:5
    at /usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:685:5
    at callback (/usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:723:5)
    at ReadStream.onData (/usr/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/index.js:775:9)
    at ReadStream.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:765:14)
    at ReadStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at ReadStream.Readable.push (_stream_readable.js:128:10)
    at TTY.onread (net.js:529:21)
undefined
```

**Comment by coolaj86** [comment]
This happens when node.js is version 0.10

I don't know why.

Putting in an error message if node version is detected to be < 4.x...
